[package]
name = "docs-as-code"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
comfy-table = "7.2.1"
serde = { version = "1.0.226", features = ["derive"] }
serde_yaml = "0.9.34"
termimad = "0.34.0"
walkdir = "2.5.0"
